### ISSUE TITLE
local-exec-provisioner-script not working

### ISSUE THREAD

**Issue by HeikoMR** [sashee/terraform-change-rds-password#1]
Hi,

I currently have problems getting your local-exec-script to run.
`aws secretsmanager get-secret-value --secret-id xxxxxx | jq -r '.SecretString' |` runs fine.

`aws secretsmanager get-secret-value --secret-id xxxxxx | jq -r '.SecretString' | jq -rM --arg PW "$PW"` fails with parse error: Invalid literal at line 2, column 0. My CLI does not like the second pipe.

**Comment by sashee** [comment]
Hey @HeikoMR ,

that's very strange! Thanks for investigating!

What system are you using? Also, a few ideas to debug:

* if you run this outside Terraform with a valid secret id, do you see the same error?
* if yes, what is the result of the working part (```aws secretsmanager get-secret-value --secret-id xxxxxx | jq -r '.SecretString'```)? Maybe that returns some data that it's not supposed to.
* could you check if you are running the full command after the second pipe (```jq -rM --arg PW "$PW" '.password = $PW'```)? I noticed the jq expression is missing from your report. Maybe that could cause some problems?

**Comment by HeikoMR** [comment]
Hi @sashee,

I found the error. In my case I only put a simple string inside `secret_string` for the terraform-resource, not key/pair values like in your case. So it probably could not find the password-key inside the secret_string and then logged the parse-error.

```
resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = "example-string-to-protect"
}
```

After switching to your `aws_secretsmanager_secret_version`-config with key/values inside the secret_string, it now works.

Thanks for your fast help and nice work.

**Comment by sashee** [comment]
Great that you solved it!
